language: go
matrix:
  include:
  - go: 1.7
install:
- make install
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: yt/9Rv8Cam3OJEAik3o4L5pP6ejB0jzqF5tQ0/t1B7u0vOQ+ct4W/LA1A9CrXTtAZSMf12lWOqB3B+9aHmLdN0vCCg1R13De+hKLsBzPLH4cMJccuSU/D97YN9A/G3QCr+HL41YSdYnBd0jjAH3BiBGr6cm2ds1EKUfpEqIE4sY5xrgkk2SCZLzymqQpGN0hcJNLNJePwW8I/Pcg4ogW4xxSyG49XNi5lyIOeGWT7O7E/JcSuHlJ/bgvP9KQGdxtiDn8JO3JxBheqUu7nZpGFEHZCYPGHL8yeqPlPBAtyoasY6gkFfLycBPdmtQJm2q9yvhjLT1EibT9fHFO2SAg44Hjb2YpDxm53hVZhmhnqWpL12pf22NSaG66KPAuLsqUuNBa+MsR9ez0CqbxHVR9ycr1d6zfJMAxQUekKVH4Cg0LmfDGVraBIBvoNFJpaV5pieeISqEUgdZe3fjxESG/3VoB+LPQ/NMdhGPP59DSoittP2CTPre7O9dc99lkbgwAIAgH+w9fdqb+sOcUljih5clefHPWwT4IWEnpPLEpXKQTeeVH9YrLf9GuAG7fsiJ4u88mDwf+4hlarNkb3yVX1UGQCdB1QgklXwEx0UK7nPg6P2nI38caZ3MFcxqZ4LsHjW2Q3vWhjREf5+gFt+9uH7UkBnUSkZaOaOB0Rhsh+d8=
  file:
  - release/goxld-linux-amd64
  - release/goxld-linux-386
  - release/goxld-windows-amd64
  - release/goxld-windows-386
  - release/goxld-osx-amd64
  skip_cleanup: true
  on:
    repo: WianVos/goxld
