language: go
matrix:
  include:
  - go: 1.7
install:
- make install
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: mvsBZVkfi9ZNH7JcPoMIUMqhuECfsXDyGzJ27MJ/bg+vJzLsIaa5ffpeLGf+KgL42mGMqzu7jPkG01gMYs3ulr8y5fS2G/EcOTFh07fsr7N/0JwT/QvKifp+yEnXROqa2NPJVJuuMKHlshddsPAhErkJzv0ahgisIuPrulbZXGfvvBETWBxrxD5azm0e2gc8gMKowGJiJ9XbGdKK1NElVDUw18ljjOBHxs7fDBvaYuIj/HbKQBEIVgsQkgMXiMiJd51xd9i50erJ1SWSHTatOVq2WralRa8u23iORSeEdLbg5MsmmYloCExUOJZAewb6ewdcZULEgrHoyDxrlonayqyrbANIjZZ327/JXqPybxhxZY5MgFDAJYFx6AHPvQtREwFtvixWbfsFnBOCAw1W70c19BvBEuRQQ2WQUiRpeiw5S2D57g7lOzvvSAU2ZBESYvTlYdYoj65Rc9frZfDGTkaE/PdHNIAgXTk4dPB/tvfvlYRXrv6NQMqDyBiHiI9B+PwaiNHiwhO0CiZLsSmnRK5zt4smfbnQXUJ7CxFFcPgu79e6zvAZiDf2/lYbOlKd/Mj4TGfHTK0Nr0cubtHfLmX334R0nUl5HPtx093O68zjMFTox2zYxLQsbiE2cizWwFNFPcp6GpE8b9Tf1dvkxPlVPCNC1qSiEw9dDBYl384=
  file:
  - release/goxld-linux-amd64
  - release/goxld-linux-386
  - release/goxld-windows-amd64
  - release/goxld-windows-386
  - release/goxld-osx-amd64
  skip_cleanup: true
  on:
    repo: WianVos/goxld
