language: go

matrix:
  include:
    - go: 1.6.3
      env: ALLOW_E2E=true # Don't run e2e tests more than once.
    - go: 1.7
    # NOTE: no tip, see https://github.com/travis-ci/gimme/issues/38



deploy:
  provider: releases
  api_key: "c3595229a48e0f7df91f2a570bd1fe57da628009"
  file: "goxld"
  skip_cleanup: true
  on:
    tags: true
