language: go
matrix:
  include:
  - go: 1.7

.PHONEY: release

release:
  mkdir -p release
  GOOS=linux GOARCH=amd64 go build -o release/myproject-linux-amd64 $(package)
	GOOS=linux GOARCH=386 go build -o release/myproject-linux-386 $(package)
	GOOS=linux GOARCH=arm go build -o release/myproject-linux-arm $(package)

deploy:
  provider: releases
  api_key:
    secure: sZ7JP2Sm8Nh9d9A2bD42H4lIHa/4y/hSckA1emXIyzvf92/oyQJg5O4IWQ4ligXzmpl0VUEDWyR3VENfEiTXWFGc/BRHEjlMfW5kzTaGwlQUZXnrsnQHLCwm7i+CAdhkPPIDfwR32IhDYenRbnfGSHGXAv1DUHOrSnyU0hPrBsrSufDEWndKbyN9yQrNWGs1T585WAnAig3MYSgqOciHgXDaDNQYNuUj7e6Nyctjbp0njotfYUuCYusN3D5K6Cl7GxTkfm46zjypTYtqZKFL6k/hswMxdoPAFG1BX8OjJF2HlDdsTdn953OPKrkwr7GvNtHCYb/R9Fs2JHno5iv540/qdzGix68GnrzjLt04WfDbKWPE18ir40dAPJ3/6W+9asuqmbxJyE83WjTy3sV5E9qhdnLZxXvvFBz5lIZ1tGAQBFnaQh1iVVTBb42RpYtSM1rst/iiIfQQYUHgupDwEXy0z5U0E9vMdDqPN9F0xhueOpughpiJJclH4JPUiPFbvC4UPJIyaFS3c9Fve2O87LDE0dpcWf6PmXCn7Yex/mmqe2M5qTEuPph5TNNP42BBHEnlAD/hMOeL1OfPkJfTS2gjKd92CIC5tdN9Fd6srgESHUxBMD68h2Njmbxm6bX7CpvkFokmUx6XdoxwEcXAGbPw0xTRUlrVOJdbTCpbN44=
  file:
    - release/myproject-linux-amd64
    - release/myproject-linux-386
    - release/myproject-linux-arm
  skip_cleanup: true
  on:
    repo: WianVos/goxld
